Feature/#98 feedbackonbuttons
MindscapeHQ/raygun4android pull request #99
Opened 2024-02-21 05:51 UTC by TheRealAgentK

### Description :memo:

Fixes #98 

Adds some Snackbar notification on actions in the sample app.

**Type of change**

*Delete options that are not relevant.*

- [x] New feature (non-breaking change which adds functionality)

**Updates**

:point_right: Added Material UI lib
:point_right: Added Snackbars on button actions, resource strings in `strings.xml`

### Author to check :eyeglasses:
- [x] Project and all contained modules build
- [x] Tested on appropriate devices/emulators and SDK versions
~- [] Reviewed by another developer~
N/A
- [x] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Change has been tested on a device/emulator
- [ ] Code is written to standards
~- [ ] Appropriate tests have been written (code comments, internal docs)~
N/A

2024-02-26 03:21 UTC, sumitramanga commented on app/src/main/res/layout/activity_second.xml
> +    tools:context=".SecondActivity">
Good catch 👍🏽

2024-02-26 03:21 UTC, sumitramanga commented on app/src/main/res/values/strings.xml
> +    <string name="we_re_now_on_the_second_activity_screen">We\'re now on the second activity screen.</string>
Nitpick: some long string names, is that usual in this space? wondering if it's ok to shorten them or does it not make sense?

2024-02-26 03:22 UTC, sumitramanga commented on app/src/main/java/com/raygun/raygun4android/sample/SecondActivity.kt
> +import java.util.WeakHashMap
Where is this used?

2024-02-26 03:22 UTC, sumitramanga commented on app/src/main/java/com/raygun/raygun4android/sample/SecondActivity.kt
> +import com.google.android.material.snackbar.Snackbar
Love it 💯 Do you have screenshots/gif/screen recording of how it looks?

2024-02-26 03:23 UTC, sumitramanga requested changes
Just some comments to address but otherwise mostly looks good! Thank you for implementing this change ⭐

2024-03-12 01:47 UTC, sumitramanga commented
Hi @TheRealAgentK ! Just wanted to check in to see if you'll have time to work on this? :)

2024-08-30 05:01 UTC, TheRealAgentK commented on app/src/main/res/values/strings.xml
> +    <string name="we_re_now_on_the_second_activity_screen">We\'re now on the second activity screen.</string>
Yeah, that is quite common in general.

2024-08-30 05:02 UTC, TheRealAgentK commented on app/src/main/java/com/raygun/raygun4android/sample/SecondActivity.kt
> +import java.util.WeakHashMap
```
val customData = WeakHashMap<String,Any>()
customData["someKey"] = "someValue"
customData["someotherkey"] = "someothervalue"
```

2024-08-30 05:03 UTC, TheRealAgentK commented on app/src/main/java/com/raygun/raygun4android/sample/SecondActivity.kt
> +import com.google.android.material.snackbar.Snackbar
Will create some and put into the repo

2024-08-30 07:37 UTC, miquelbeltran approved these changes

2024-08-30 07:39 UTC, miquelbeltran commented on app/src/main/java/com/raygun/raygun4android/sample/MainActivity.kt
> +            Snackbar.make(it, getString(R.string.user_is_now_set_to_anonymous_for_future_raygun_reports),Snackbar.LENGTH_SHORT).show()
```suggestion
            Snackbar.make(it, getString(R.string.user_is_now_set_to_anonymous_for_future_raygun_reports), Snackbar.LENGTH_SHORT).show()
```

Small thing, just a formatting change. It's also present in the `Snackbar.make` calls.

2024-08-30 07:53 UTC, TheRealAgentK commented on app/src/main/java/com/raygun/raygun4android/sample/MainActivity.kt
> +            Snackbar.make(it, getString(R.string.user_is_now_set_to_anonymous_for_future_raygun_reports),Snackbar.LENGTH_SHORT).show()
I might leave it as is for now, one of the next things this needs is a linter setup and formatting at build etc anyway.

2024-08-30 23:43 UTC, merged